[package]
name = "ouroboros"
version = "0.3.0"
authors = ["DanieleDiBenedetto <daniele@horizenlabs.io>"]
edition = "2018"

[dependencies]
algebra = { git = "https://github.com/HorizenOfficial/ginger-lib.git",  tag = "0.2.0"}
primitives = { features = ["vrf"], git = "https://github.com/HorizenOfficial/ginger-lib.git",  tag = "0.2.0"}
rand = { version = "0.7" }

