[package]
name = "ouroboros"
version = "0.1.0"
authors = ["DanieleDiBenedetto <daniele@horizenlabs.io>"]
edition = "2018"

[dependencies]
algebra = {version = "0.1.0", git = "https://github.com/HorizenLabs/ginger-lib", branch = "new_structure"}
primitives = {version = "0.1.0", features = ["vrf"], git = "https://github.com/HorizenLabs/ginger-lib", branch = "new_structure"}
rand = { version = "0.7" }

