[package]
name = "ouroboros"
version = "0.1.0"
authors = ["DanieleDiBenedetto <daniele@horizenlabs.io>"]
edition = "2018"

[dependencies]
algebra = {version = "0.1.0", features = ["tweedle"], git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "integration"}
primitives = {version = "0.1.0", features = ["tweedle", "vrf"], git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "integration"}
rand = { version = "0.7" }

[features]
default = [ "asm" ]
asm = [ "algebra/llvm_asm" ]
