[package]
name = "demo-circuit"
version = "0.1.0"
authors = ["DanieleDiBenedetto <daniele@horizenlabs.io>"]
edition = "2018"
include = ["Cargo.toml", "src"]

[dependencies]
algebra = {version = "0.1.0", git = "https://github.com/HorizenLabs/ginger-lib", branch = "new_structure"}
primitives = {version = "0.1.0", features = ["signature"], git = "https://github.com/HorizenLabs/ginger-lib", branch = "new_structure"}
r1cs-crypto = {version = "0.1.0", features = ["signature"], git = "https://github.com/HorizenLabs/ginger-lib", branch = "new_structure"}
r1cs-core = {version = "0.1.0", git = "https://github.com/HorizenLabs/ginger-lib", branch = "new_structure"}
r1cs-std = {version = "0.1.0", git = "https://github.com/HorizenLabs/ginger-lib", branch = "new_structure"}
proof-systems = {version = "0.1.0", features = ["groth16"], git = "https://github.com/HorizenLabs/ginger-lib", branch = "new_structure"}

digest = "0.7"
blake2s_simd = "0.5"

derivative = "1"
lazy_static = "1"
radix_trie = "0.1"
rand = { version = "0.7" }
