[package]
name = "demo-circuit"
version = "0.1.0"
authors = ["DanieleDiBenedetto <daniele@horizenlabs.io>"]
edition = "2018"
include = ["Cargo.toml", "src"]

[dependencies]
algebra = { git = "https://github.com/HorizenOfficial/ginger-lib.git",  tag = "0.2.0"}
primitives = { features = ["signature"], git = "https://github.com/HorizenOfficial/ginger-lib.git",  tag = "0.2.0"}
r1cs-crypto = { features = ["signature"], git = "https://github.com/HorizenOfficial/ginger-lib.git",  tag = "0.2.0"}
r1cs-core = { git = "https://github.com/HorizenOfficial/ginger-lib.git",  tag = "0.2.0"}
r1cs-std = { git = "https://github.com/HorizenOfficial/ginger-lib.git",  tag = "0.2.0"}
proof-systems = { features = ["groth16"], git = "https://github.com/HorizenOfficial/ginger-lib.git",  tag = "0.2.0"}

derivative = "1"
lazy_static = "1"
radix_trie = "0.1"
rand = { version = "0.7" }

[dev-dependencies]
digest = "0.7"
blake2s_simd = "0.5"
bit-vec = "0.6.1"