[package]
name = "api"
version = "0.1.0"
authors = ["DanieleDiBenedetto <daniele@horizenlabs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebra = {version = "0.1.0", features = ["tweedle"], git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "misc_changes"}
primitives = {version = "0.1.0", features = ["tweedle", "merkle_tree"], git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "misc_changes"}

cctp_primitives = { git = "https://github.com/HorizenOfficial/zendoo-cctp-lib.git", branch = "limit_proof_vk_size" }

#ouroboros = {path = "../ouroboros"}
demo-circuit = {path = "../demo-circuit"}

jni = "0.6.1"
derivative = "1"
lazy_static = "1"
radix_trie = "0.1"
rand = { version = "0.7" }
rand_xorshift = { version = "0.2" }
blake2 = { version = "0.8", default-features = false }

[features]
asm = ["algebra/llvm_asm"]

[lib]
name = "zendoo_sc"
path = "src/lib.rs"
crate_type = ["cdylib"]
